<?
    namespace application\models;
    
    use \smashEngine\core\App AS App; 
    use \PDO;
    
	class styleCategory extends \smashEngine\core\Model
	{
		public static $dbtable = 'styles_category';
		
		public static $BASECATS = array(
		    // специально стоят в самом верху (не убирать)
		    // чтобы в конструкторе они шли самыми первыми
		    'opt' => array(
                'id' => 113, 
                'title' => 'Оптовые носители',
                'sexes' => array('male', 'female'),
                'src_name'  => 'ps_src',
                'def_side'    => 'front',
                'def_real_w' => array('front' => 210, 'back' => 290),
            ),
			'futbolki' => array(
				'id' => 2,
			    'title'          => 'Футболки',
			    'title_lower'    => 'футболки',
			    'title_2'        => 'футболкам',
			    'title_genitive' => 'футболку',
			    'title_single'   => 'Футболка',
			    'title_rp'       => 'футболок',
			    'sexes'       => array('male', 'female', 'kids'),
			    'def_color'   => array('male' => 37, 'female' => 37, 'kids' => 37),
				'def_style'   => array('male' => 407, 'female' => 429, 'kids' => 390),
				'def_side'    => 'front',
				'def_real_w'  => array('front' => 210, 'back' => 290),
				'src_name'    => 'ps_src',
				'src' => array('w' => 1800, 'h' => 2500),
				'promo_color' => array('male' => 53, 'female' => 53),
				'promo_styles'=> array('male' => array(510, 407, 408), 'female' => array(509, 429, 436), 'kids' => array(390)),
				'promo'       => array(407, 429, 408, 436, 390),
			),
            'tolstovki' => array(
                'id' => 17,
                'title'       => 'Толстовки',
                'title_lower' => 'толстовки',
                'title_2'       => 'толстовкам',
                'title_genitive' => 'толстовку',
                'title_single'   => 'Толстовка',
                'title_rp'       => 'толстовок',
                'sexes'       => array('male', 'female'),
                'def_color'   => array('male' => 21, 'female' => 21),
                'def_style'   => array('male' => 376, 'female' => 369),
                'def_side'    => 'front',
                'def_real_w'  => array('front' => 210, 'back' => 290),
                'src_name'    => 'ps_src',
                'src'         => array('w' => 1800, 'h' => 2500),
                'promo_color' => array('male' => 112, 'female' => 111),
                'promo_styles'=> array('male' => array(376, 378, 504), 'female' => array(369, 502)),
                'promo'       => array(376, 369),
            ),
            'sweatshirts' => array(
                'id' => 70,
                'title'       => 'Свитшоты',
                'title_lower' => 'свитшоты',
                'title_2'       => 'свитшотам',
                'title_genitive' => 'свитшот',
                'title_single'   => 'Свитшот',
                'title_rp'       => 'свитшотов',
                'sexes'       => array('male', 'female', 'kids'),
                'def_color'   => array('male' => 21, 'female' => 21, 'kids' => 30),
                'def_style'   => array('male' => 378, 'female' => 502, 'kids' => 718),
                'def_side'    => 'front',
                'def_real_w'  => array('front' => 210, 'back' => 290),
                'src_name'    => 'ps_src',
                'src'         => array('w' => 1800, 'h' => 2500),
                'promo_color' => array('male' => 112, 'female' => 111),
                'promo_styles'=> array('male' => array(376, 378, 504), 'female' => array(369, 502, 915), 'kids' => array(718, 899)),
                'promo'       => array(378, 502, 718,915,899),
                'parent'      => 'tolstovki',
            ),
			'patterns' => array(
				'id' => 86,
			    'title'       => 'Футболки 3D',
			    'title_genitive' => 'футболку',
			    'title_single'   => 'Футболка',
			    'title_rp'       => 'футболок 3D',
			    'title_2'       => 'футболкам 3D',
			    'sexes'       => array('male', 'female'),
			    'def_color'   => array('male' => 37, 'female' => 37),
				'def_side'    => 'front',
				'src_name'    => 'patterns',
				'def_style'   => array('female' => 752, 'male' => 621),
				'promo'       => array(752, 621),
				'src' => array('w' => 5900, 'h' => 6300),
			),
			'patterns-sweatshirts' => array(
				'id' => 88,
			    'title'       => 'Свитшоты 3D',
			    'title_genitive' => 'свитшот',
			    'title_single'   => 'Свитшот',
			    'title_rp'       => 'свитшотов 3D',
			    'title_2'       => 'свитшотам 3D',
			    'sexes'       => array('male', 'female', 'kids'),
			    'def_color'   => array('male' => 111, 'female' => 111),
				'def_side'    => 'front',
				'src_name'    => 'patterns',
				'def_style'   => array('male' => 620, 'female' => 620, 'kids' => 825),
				'promo'       => array(619, 620, 825),
				'src' => array('w' => 5900, 'h' => 6300),
			),
			'patterns-tolstovki' => array(
                'id' => 122,
                'title'       => 'Толстовки 3D',
                'title_genitive' => 'толстовка',
                'title_single'   => 'Толстовка',
                'title_rp'       => 'Толстовок 3D',
                'title_2'       => 'толстовкам 3D',
                'sexes'       => array('male', 'female'),
                'def_color'   => array('male' => 111, 'female' => 111),
                'def_side'    => 'front',
                'src_name'    => 'patterns',
                'def_style'   => array('male' => 830, 'female' => 832),
                'promo'       => array(830, 832),
                'src' => array('w' => 5900, 'h' => 6300),
            ),
			'patterns-bag' => array(
                'id' => 100,
                'title'       => 'Сумки с полной запечаткой',
                'title_2'        => 'сумкам с полной запечаткой',
                'title_genitive' => 'сумка',
                'title_single'   => 'Сумка',
                'sexes'       => array('female'),
                'def_side'    => 'front',
                'src_name'    => 'patterns_bag',
                'def_style'   => array('female' => 744),
                'promo'       => array(744),
                'src' => array('w' => 4720, 'h' => 5430),
            ),
			'patterns-dress' => array(
                'id' => 115,
                'title'       => 'Платья с полной запечаткой',
                'title_genitive' => 'платье',
                'sexes'       => array('female'),
                'def_color'   => array('female' => 795),
                'def_side'    => 'front',
                'src_name'    => 'patterns',
                'def_style'   => array('female' => 795),
                'promo'       => array(795),
                'src' => array('w' => 5900, 'h' => 6300),
            ),
			'textile' => array(
				'id'          => 105,
			    'title'       => 'Ткань',
			    'title_genitive' => 'ткань',
				'def_side'    => 'front',
				'src_name'    => 'patterns',
				'def_style'   => array('female' => 754),
				//'promo'       => array(754,),
				'src' => array('w' => 5900, 'h' => 6300),
			),
			'futbolki_bez_birki' => array(
				'id'          => 87,
			    'title'       => 'Футболки без бирки',
			    'sexes'       => array('male', 'female'),
				'def_side'    => 'front',
				'src_name'    => 'ps_src',
			),
			'longsleeve_tshirt' => array(
				'id' => 3,
			    'title'       => 'Футболки лонгсливы',
			    'title_lower' => 'Футболки лонгсливы',
			    'title_2' => 'футболкам лонгсливам',
			    'title_genitive' => 'футболку лонгслив',
			    'sexes'       => array('male', 'female'),
			    'def_color'   => array('male' => 131, 'female' => 53),
				'def_style'   => array('male' => 733, 'female' => 623),
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
				'src_name'  => 'ps_src',
				'src' => array('w' => 1800, 'h' => 2500),
				'promo_color' => array('male' => 53, 'female' => 53),
				'promo'       => array(575, 733),
				'parent'      => 'futbolki',
			),
			'polo' => array(
				'id' => 24,
			    'title'       => 'Поло',
			    'title_lower' => 'поло',
			    'title_2'       => 'поло',
			    'sexes'       => array('male', 'female'),
			    'def_color'   => array('male' => 53, 'female' => 53),
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
				'src_name'  => 'ps_src',
				'promo_color' => array('male' => 53, 'female' => 53),
				'promo_styles'=> array('male' => array(510, 544), 'female' => array(509, 542)),
			),
			'cap' => array(
                'id' => 444,
                'title'       => 'Бейсболка',
                'title_lower' => 'бейсболка',
                'title_2'       => 'Бейсболка',
                'sexes'       => array('male', 'female'),
                'src_name'  => 'ps_src',
            ),
			'mayki' => array(
				'id' => 72,
			    'title'       => 'Майки',
			    'title_lower' => 'Майки',
			    'title_2'       => 'майкам',
			    'title_genitive' => 'майку',
			    'sexes'       => array('female'),
				'src_name'    => 'ps_src',
				'src' => array('w' => 1800, 'h' => 2500),
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
			),
			'mayki-alkogolichki' => array(
				'id' => 6,
			    'title'       => 'Майки-борцовки',
			    'title_lower' => 'Майки-борцовки',
			    'title_2'       => 'майкам-борцовкам',
			    'title_genitive' => 'майку',
			    'title_single'   => 'Майка',
			    'title_rp' => 'маек борцовок',
			    'sexes'       => array('female'),
				'def_color'   => array('female' => 37),
				'def_style'   => array('female' => 454,),
				'promo_styles'=> array('female' => array(453)),
				'promo'       => array(453),
				'src_name'  => 'ps_src',
				'src' => array('w' => 1800, 'h' => 2500),
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
			),
			'sumki' => array(
				'id' => 10,
			    'title'       => 'Сумки',
			    'title_lower' => 'Сумки',
			    'title_2'       => 'сумкам',
			    'title_genitive' => 'сумку',
			    'sexes'       => array('female'),
				'def_color'   => array('female' => 71),
				'promo_styles'=> array('female' => array(478)),
				'promo'       => array(),
				'src_name'    => 'ps_src',
				'src' => array('w' => 1800, 'h' => 2500),
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
			),
			'platya' => array(
				'id' => 9,
			    'title'       => 'Платья',
			    'title_lower' => 'Платья',
			    'title_2'       => 'платьям',
			    'title_genitive' => 'платье',
			    'sexes'       => array('female'),
			    'def_color'   => array('female' => 21),
				'src_name'    => 'ps_src',
				'def_side'    => 'front',
				'src' => array('w' => 1800, 'h' => 2500),
				'def_real_w' => array('front' => 210, 'back' => 290),
			),
			'body' => array(
                'id' => 123,
                'title'          => 'Боди',
                'title_lower'    => 'боди',
                'title_2'        => 'боди',
                'title_genitive' => 'боди',
                'title_single'   => 'боди',
                'title_rp'       => 'боди',
                'sexes'          => ['female'],
                'def_color'      => ['female' => 111],
                'def_style'      => ['female' => 922],
                'def_side'       => 'front',
                'src_name'       => 'patterns',
                'promo'          => [922],
                'src'            => ['w' => 5900, 'h' => 6300],
            ),
            'bomber' => array(
                'id' => 124,
                'title'          => 'Бомбер',
                'title_lower'    => 'бомбер',
                'title_2'        => 'бомберам',
                'title_genitive' => 'бомбер',
                'title_single'   => 'бомбер',
                'title_rp'       => 'бомберов',
                'sexes'          => ['female'],
                'def_color'      => ['female' => 111],
                'def_style'      => ['female' => 923],
                'def_side'       => 'front',
                'src_name'       => 'patterns',
                'promo'          => [923],
                'src'            => ['w' => 5900, 'h' => 6300],
            ),
			'svoya_futbolka' => array(
			     'id' => 71,
				'title' => 'Своя футболка светлая',
				'title_genitive' => 'футболку',
				'sexes' => array('unisex'),
				'src_name'  => 'ps_src',
				'def_side'    => 'front',
				'def_real_w' => array('front' => 210, 'back' => 290),
			),
			'svoya_futbolka_temnaya' => array(
                 'id' => 118,
                'title' => 'Своя футболка тёмная',
                'title_genitive' => 'футболку',
                'sexes' => array('unisex'),
                'src_name'  => 'ps_src',
                'def_side'    => 'front',
                'def_real_w' => array('front' => 210, 'back' => 290),
            ),
			'phones' => array(
				'id'              => 22,
				'title'           => 'Телефон',
				'title1'          => 'Телефона',
	            'title_catalog'   => 'iPhone5/чехлы',
	            'title_customize' => 'Наклейки на телефон',
	            'title_lower'     => 'наклейки на телефон',
	            'title_genitive'  => 'наклейку на телефон',
	            'title_2'         => 'телефонам',
				'src_min_w'   => 500,
				'src_min_h'   => 0,
				'def_side'    => 'back',
				'def_style'   => 333,
				'def_real_w'  => array('front' => 60, 'back' => 60),
				'sides'       => array('front', 'back'),
				'src'         => array('w' => 725, 'h' => 1385),
				'src_name'    => 'phones',
				'promo'       => array(333, 630),
			),
			'touchpads' => array(
				'id'	   	   => 60,
				'title' 	   => 'Планшет',
				'title1' 	   => 'Планшета',
				'title_lower'  => 'наклейки на планшет',
				'title_2'      => 'планшетам',
				'title_genitive'  => 'наклейку на планшет',
				'src_min_w'    => 500,
				'src_min_h'    => 0,
				'def_side'     => 'back',
				'def_style'    => 511,
				'def_real_w'   => array('front' => 190, 'back' => 190),
				'sides'        => array('front', 'back'),
				'src'          => array('w' => 3600, 'h' => 4600),
				'src_name'     => 'touchpads',
				'promo'        => array(734),
			),
			'laptops' => array(
				'id'		=> 21,
				'title' 	=> 'Ноутбук',
				'title1' 	=> 'Ноутбука',
				'title_lower'   => 'наклейки на ноутбук',
				'title_2'       => 'ноутбукам',
				'title_genitive'  => 'наклейку на ноутбук',
				'src_min_w' => 500,
				'src_min_h' => 345,
				'def_side'  => 'front',
				'def_style' => 818, //342
				'def_real_w' => array('front' => 325, 'back' => 227),
				'sides'     => array('front'),
				'src'       => array('w' => 4600, 'h' => 3600),
				'src_name'  => 'laptops',
				'promo'       => array(834),
			),
			'ipodmp3' => array(
				'id'		=> 59,
				'title' 	=> 'iPod&MP3',
				'title1' 	=> 'Плеера',
				'title_lower' => 'плееры',
				'title_2'     => 'плеерам',
				'title_genitive'  => 'наклейку на плеер',
				'src_min_w'   => 500,
				'src_min_h'   => 0,
				'def_side'    => 'back',
				'def_style'   => 351, //263
				'def_real_w'  => array('front' => 60, 'back' => 60),
				'sides'       => array('front', 'back'),
				'src'         => array('w' => 1200, 'h' => 1800),
				'src_name'    => 'phones',
				'promo'       => array(),
 			),
			'cases' => array(
				'id'		=> 73,
				'title' 	=> 'Чехлы',
				'title1' 	=> 'Чехла',
				'title_customize' => 'Чехлы для телефона',
				'title_lower'   => 'чехлы',
				'title_2'       => 'чехлам',
				'title_genitive'  => 'чехол для телефона',
				'src_min_w' => 500,
				'src_min_h' => 0,
				'def_side'  => 'back',
				'def_style' => 315,
				'def_real_w' => array('front' => 60, 'back' => 60),
				'sides'     => array('front', 'back'),
				'src'       => array('w' => 1165, 'h' => 1635),
				'src_name'  => 'phones',
				'promo'       => array(354,643,720),
			),
			'poster' => array(
				'id'		  => 23,
				'title'   	     => 'Постер',
				'title_lower'    => 'постеры',
				'title_2'        => 'постерам',
				'title_genitive' => 'постер',
				'src_min_w'   => 500,
				'src_min_h'   => 0,
				'def_side'    => 'front',
                'def_style'   => 521,
                'def_style_p' => array('vertical' => 520, 'horizontal' => 532, 'square' => 539,),
				'src_name'    => 'poster',
				'src'         => array('w' => 2100, 'h' => 3000),
				'pxPerCm'     => 59,
				'promo'       => array(513, 517, 529),
			),
			'cup' => array(
				'id'		  => 98,
				'title'   	     => 'Кружки',
				'title_lower'    => 'кружки',
				'title_2'        => 'Кружкам',
				'title_genitive' => 'кружка',
				'src_min_w'   => 2480,
				'src_min_h'   => 830,
				'def_side'    => 'front',
                'def_style'   => 725,
				'src_name'    => 'cup',
				'promo'       => array(725),
				'src'          => array('w' => 2680, 'h' => 1090),
			),
			'bag' => array(
				'id'		  => 103,
				'title'   	     => 'Рюкзаки',
				'title_lower'    => 'рюкзаки',
				'title_2'        => 'Рюкзакам',
				'title_genitive' => 'рюкзак',
				'src_min_w'   => 2480,
				'src_min_h'   => 830,
				'def_side'    => 'front',
                'def_style'   => 749,
				'src_name'    => 'patterns',
				'src'          => array('w' => 2480, 'h' => 830),
				'promo'       => array(749),
			),
			'pillows' => array(
				'id'		  => 106,
				'title'   	     => 'Подушки',
				'title_lower'    => 'подушки',
				'title_2'        => 'Подушкам',
				'title_genitive' => 'подушка',
				'src_min_w'   => 2500,
				'src_min_h'   => 2500,
				'def_side'    => 'front',
                'def_style'   => 758,
				'src_name'    => 'patterns',
				'src'          => array('w' => 2500, 'h' => 2500),
				'promo'       => array(758),
			),
			'auto' => array(
				'id'		  => 65,
				'title' 	  => 'Авто-наклейки',
				'title_lower' => 'авто-наклейки',
				'title_2'     => 'авто-наклейкам',
				'title_genitive'  => 'авто-наклейку',
				'src_min_w'   => 500,
				'src_min_h'   => 0,
				'def_side'    => 'front',
				'def_style'   => 288,
				'src_name'    => 'auto',
				'promo'       => array(288, 629),
			),
			'moto' => array(
				'id'		=> 81,
				'title' 	=> 'Наклейки на бак мотоцикла',
				'title_2'       => 'наклейкам на бак мотоцикла',
				'title_genitive'  => 'наклейку на бак мотоцикла',
				'src_min_w' => 500,
				'src_min_h' => 0,
				'def_side'  => 'back',
				'def_style' => 467,
				'def_real_w' => array('front' => 200, 'back' => 200),
				'src_name'  => 'touchpads',
				'src'          => array('w' => 3600, 'h' => 4600),
				'prv'     => array('w' => 358, 'h' => 366),
				'promo'       => array(467),
			),
			'boards' => array(
				'id'		  => 84,
				'title'   	  => 'Доски',
				'title_2'       => 'доскам',
				'title_genitive'  => 'наклейку на доску',
				'src_min_w'   => 0,
				'src_min_h'   => 500,
				'def_side'    => 'front',
                'def_style'   => 593,
				'src_name'    => 'boards',
				'promo'       => array(593),
				'src' => array('w' => 5900, 'h' => 6300),
			),
			'stickerset' => array(
				'id'    => 83,
				'title' => 'Стикерсеты',
				'title_genitive'  => 'стикерсет',
				'src_name'  => 'stickerset',
				'def_side'    => 'front',
			),
			'stickers' => array(
				'title' => 'Наклейки',
				'id'    => 85,
				'src_name'  => 'stickers',
				'title_genitive'  => 'наклейку',
				'def_side'    => 'front',
				'src' => array('w' => 600, 'h' => 200),
			),
			'postcards' => array(
				'title' => 'Открытка',
			),
			'windbreaker' => array(
                'title' => 'Ветровка',
            ),
            'jacket' => array(
                'title' => 'Жилет',
            ),
		);
		
		public static $BASECATSid = array(
			2 => 'futbolki',
			3 => 'longsleeve_tshirt',
			6 => 'mayki-alkogolichki',
			17 => 'tolstovki',
			70 => 'sweatshirts',
			22 => 'phones',
			21 => 'laptops',
			23 => 'poster',
			24 => 'polo',
			59 => 'ipodmp3',
			60 => 'touchpads',
			65 => 'auto',
			81 => 'moto',
			73 => 'cases',
			76 => 'postcards',
			83 => 'stickerset',
			84 => 'boards',
			85 => 'stickers',
			86 => 'patterns',
			88 => 'patterns-sweatshirts',
			100 => 'patterns-bag',
			115 => 'patterns-dress',
			122 => 'patterns-tolstovki',
			98  => 'cup',
			103 => 'bag',
			105 => 'textile',
			106 => 'pillows',
			123 => 'body',
			124 => 'bomber',
		);
		
		public static function findAll($params)
		{
			$r = App::db()->query("SELECT c.*
				FROM `" . self::$dbtable . "` c
				WHERE
					1 
					"
					. 
					($params['gadgets'] ? "AND c.`cat_parent` > '1'" : '')
					. 
					($params['parent'] ? "AND c.`cat_parent` IN ('" . implode("', '", (array) $params['parent']) . "')" : '')
					.
					"
				ORDER BY c.`left_key`");
				
			$cats = $r->fetchAll();
				
			return $cats;
		}
	}
?>